
- name: Ensure VLAN 50 exists with the name WEB and is in the shutdown state
  nxos_vlan:
    vlan_id: 60
    host: "{{ inventory_hostname }}"
    admin_state: up
    name: WEBGROUP
    transport: nxapi
    username: cisco
    password: cisco
