---
- name: sample playbook
  hosts: nxapi
  connection: local
  tasks:
    - name: add VLAN
      nxos_vlan:
        vlan_id: 59 
        host: "{{ inventory_hostname }}"
        admin_state: up
        name: HYUNGSOK_VLAN_59 
        transport: nxapi
        username: cisco
        password: cisco
